In [1]:
# numpy
import numpy as np

In [3]:
# Cria uma matriz unidimensional
mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [9]:
# Criar array com um tipo especifico
# cria o array como float de 64 bits
mtfloat = np.array([1,2,3], dtype = np.float64)
print(mtfloat)
mtint = np.array([1,2,3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
[1 2 3]
<class 'numpy.ndarray'>


In [11]:
# mudar o tipo do array
# Podemos transformar tipos de dados de arrays
mtnew = np.array([1.4, 3.6, -5.1, 9,42, 4.999999])
print(mtnew)
# quando transformamos de float para int os valores são truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4       3.6      -5.1       9.       42.        4.999999]
[ 1  3 -5  9 42  4]


In [13]:
# podemos fazer o inverso tambem
mt5 = np.array([1,2,3,4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [14]:
# mais de uma dimensão
# cria uma matriz bidimensional
mt7 = np.array([[7,2,23], [12,27,4],[5,34,23]])
print(mt7)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [15]:
# mais de uma dimensão
# cria um matriz bidimensional
mt7 = np.array([[7,2,23],[12,27,4],[5,34,23]])
print(mt7)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [23]:
# arrays vazios tipificados
# empty siginifica que não são inicializados, não que são vazios
vazio = np.empty([3,2],dtype = int)
print(vazio)
print("------")
# cria matriz com os valores 4x3 com valores zeros
zeros = np.zeros([4,3])
print(zeros)
print("-----------")
# com valores igual a um 
um = np.ones([5,7])
print(um)
# cria matriz quadrada com diagonal principal 1 e os outros zero
diagoal = np.eye(5)
print(diagoal)

[[ -305020864         377]
 [          0           0]
 [          1 -2147483648]]
------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-----------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [4]:
# valores aliatorios entre zero e um
ale = np.random.random((5))
print(ale)
print("-----------------")
# valores aleatorios distr. normal contendo negativos
ale2 = np.random.randn((5))
print(ale2)
print("-------------------")
# valores aleatorios 3x4
ale3 = (10*np.random.random((3,4)))
print(ale3)

NameError: name 'np' is not defined